### ISSUE TITLE
More schedule options

### ISSUE THREAD

**Issue by ArtieFuzzz** [io7m-com/exfilac#19] opened 2024-10-08 06:48 UTC
Would it be possible to add more schedule options (2h, 4h, 8h, 24h, etc.) or have the ability to add custom schedules (check directory at a certain day and time during the day)?

**Comment by io7m** [comment] 2024-10-08 08:43
Yes indeed!

There are some [issues](#17) on newer devices that need to be fixed first, but I'll keep this in mind for the next version.

**Comment by io7m** [comment] 2024-10-11 10:34
This will be in `1.1.0` which will be tagged this weekend. It'll take at least a few days for new F-Droid builds to appear, though.

I should say that, although there are now options to run at most every 24 hours, you probably should aim to run more frequently than that. Is there some reason you need to run with such infrequent backups?

If it's a bandwidth issue, you should probably be aware that when `exfilac` saves a file into S3, it stores the SHA-256 hash of that file on the server as metadata. The next time a backup runs, it'll compare that remotely-saved SHA-256 hash with the local hash value and it won't send the file again if the hashes match. This can mean that, if you have a thousand files locally that aren't changing, you'll only pay the cost of ~1000 relatively cheap `HEAD` requests to the server, instead of paying the cost of ~1000 file uploads. :slightly_smiling_face:

**Comment by ArtieFuzzz** [comment] 2024-10-11 10:47
I mainly use `exfilac` to backup my Molly (Signal) messages to a S3 bucket and I've set Molly to create a single backup at the end of the week. It feels awkward to be checking so often.

Sorry if I didn't provide the reason as to why I made the suggestion

**Comment by io7m** [comment] 2024-10-11 11:07
> I mainly use `exfilac` to backup my Molly (Signal) messages to a S3 bucket and I've set Molly to create a single backup at the end of the week. It feels awkward to be checking so often.

The problem is that, if the weekly backup fails (and you don't notice it failing), then it'll be another week before the backup has another chance to run. You run the (admittedly not huge) risk of missing the backup every week. On a system like Android that basically can't give any guarantees, you probably want to be running backups more frequently.

> Sorry if I didn't provide the reason as to why I made the suggestion

No need to apologize!

**Closed** 2024-10-12 12:35 UTC
